package top.theillusivec4.champions.common.registry;

import net.minecraft.core.registries.Registries;
import net.minecraft.data.worldgen.BootstapContext;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.damagesource.DamageEffects;
import net.minecraft.world.damagesource.DamageScaling;
import net.minecraft.world.damagesource.DamageType;
import top.theillusivec4.champions.common.utils.Utils;

/**
 * Custom damage type keys used by the Champions mod.
 *
 * <p>JSON definitions live at {@code data/champions/damage_type/*.json} and are
 * generated by {@link top.theillusivec4.champions.common.datagen.DamageTypeProvider}.</p>
 */
public final class ModDamageTypes {

    private ModDamageTypes() {}

    /** Reflected damage (Reflective affix). Guards against infinite reflection loops. */
    public static final ResourceKey<DamageType> REFLECTION = key("reflection");

    /** Homing fire bullet (Enkindling affix). Tagged as IS_FIRE in tags datagen. */
    public static final ResourceKey<DamageType> ENKINDLING_BULLET = key("enkindling_bullet");

    private static ResourceKey<DamageType> key(String path) {
        return ResourceKey.create(Registries.DAMAGE_TYPE,
                Utils.key(path));
    }

    /**
     * for data generation
     */
    public static void bootstrap(BootstapContext<DamageType> context) {
        context.register(REFLECTION, new DamageType("reflection", DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER, 0.1F));
        context.register(ENKINDLING_BULLET, new DamageType("enkindling_bullet", DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER, 0.1F, DamageEffects.BURNING));
    }
}
