package top.theillusivec4.champions.common.client.screen.editor;

import net.minecraft.client.resources.language.I18n;

/**
 * Tiny helper for localizing editor screen strings.
 *
 * <p>Form rows, headers, hints and action buttons are rendered as plain
 * strings, so panes resolve translation keys through {@link #tr(String)} at
 * build time. Keys live under {@code gui.champions.editor.*} /
 * {@code gui.champions.picker.*} in {@code assets/champions/lang/*.json}
 * (generated by {@code ChampionLanguageProvider}).</p>
 */
public final class EditorLang {

    private EditorLang() {}

    /** {@code I18n.get(key)} — falls back to en_us when the key is missing. */
    public static String tr(String key) {
        return I18n.get(key);
    }

    /** {@code I18n.get(key, args)} with {@code %s} placeholders. */
    public static String tr(String key, Object... args) {
        return I18n.get(key, args);
    }
}
