package top.theillusivec4.champions.common.datagen;
import top.theillusivec4.champions.common.utils.Utils;

import com.mojang.serialization.Codec;
import com.mojang.serialization.JsonOps;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import org.jetbrains.annotations.NotNull;
import top.theillusivec4.champions.api.champion.ChampionTier;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;

/**
 * Generates {@code data/<namespace>/champions/tier/*.json} tier definition files.
 *
 * <p>Call {@link #tier(String, int, int)} to register each tier, then add this
 * provider to your {@code GatherDataEvent} with {@code event.includeServer()}.</p>
 *
 * <h3>Default tiers generated by {@link #addDefaultTiers()}:</h3>
 * <pre>
 * Tier 1 — white  (#FFFFFF)
 * Tier 2 — aqua   (#55FFFF)
 * Tier 3 — yellow (#FFFF55)
 * Tier 4 — red    (#FF5555)
 * Tier 5 — purple (#FF55FF)
 * </pre>
 */
public class TierProvider implements DataProvider {

    // ── Wire codec (mirrors TierDataLoader's internal TierSpec codec) ─────────

    private static final Codec<ChampionTier.TierDisplay> DISPLAY_CODEC =
            RecordCodecBuilder.create(inst -> inst.group(
                    Codec.INT.optionalFieldOf("color", 0xFFFFFFFF)
                            .forGetter(ChampionTier.TierDisplay::color),
                    ResourceLocation.CODEC
                            .optionalFieldOf("icon",
                                    new ResourceLocation("minecraft", "textures/gui/icons.png"))
                            .forGetter(ChampionTier.TierDisplay::icon)
            ).apply(inst, ChampionTier.TierDisplay::new));

    /** Serializable spec for one tier file body. */
    private record TierSpec(
            int level,
            ChampionTier.TierDisplay display
    ) {
        static final Codec<TierSpec> CODEC =
                RecordCodecBuilder.create(inst -> inst.group(
                        Codec.INT.fieldOf("level")
                                .forGetter(TierSpec::level),
                        DISPLAY_CODEC.fieldOf("display")
                                .forGetter(TierSpec::display)
                ).apply(inst, TierSpec::new));
    }

    // ── Builder ───────────────────────────────────────────────────────────────

    private record TierEntry(ResourceLocation id, TierSpec spec) {}

    private final PackOutput output;
    private final List<TierEntry> tiers = new ArrayList<>();

    public TierProvider(PackOutput output) {
        this.output = output;
    }

    /**
     * Register a tier to be generated.
     *
     * @param namespace  namespace of the output file (usually {@code "champions"})
     * @param name       path component of the file name, e.g. {@code "tier_1"}
     * @param level      numeric level used for ordering / tier selection
     * @param color      ARGB-packed display color (use {@link #argb(int, int, int, int)})
     * @return {@code this} for chaining
     */
    public TierProvider tier(String namespace, String name, int level, int color) {
        ResourceLocation id = Utils.key(namespace, name);
        ChampionTier.TierDisplay display = new ChampionTier.TierDisplay(
                color,
                new ResourceLocation("minecraft", "textures/gui/icons.png")
        );
        tiers.add(new TierEntry(id, new TierSpec(level, display)));
        return this;
    }

    /** Convenience overload — namespace defaults to {@code "champions"}. */
    public TierProvider tier(String name, int level, int color) {
        return tier("champions", name, level, color);
    }

    /**
     * Add the five default tiers matching the hard-coded fallback colors in
     * {@link ChampionTier.TierDisplay#defaultFor(int)}.
     */
    public TierProvider addDefaultTiers() {
        tier("tier_1", 1, 0xFFFFFFFF); // white
        tier("tier_2", 2, 0xFF55FFFF); // aqua
        tier("tier_3", 3, 0xFFFFFF55); // yellow
        tier("tier_4", 4, 0xFFFF5555); // red
        tier("tier_5", 5, 0xFFFF55FF); // purple
        return this;
    }

    // ── DataProvider ──────────────────────────────────────────────────────────

    @Override
    public @NotNull CompletableFuture<?> run(@NotNull CachedOutput cache) {
        List<CompletableFuture<?>> futures = new ArrayList<>();
        for (TierEntry entry : tiers) {
            Path path = output.getOutputFolder()
                    .resolve("data")
                    .resolve(entry.id().getNamespace())
                    .resolve("champions/tier")
                    .resolve(entry.id().getPath() + ".json");

            futures.add(TierSpec.CODEC.encodeStart(JsonOps.INSTANCE, entry.spec())
                    .resultOrPartial(System.err::println)
                    .map(json -> DataProvider.saveStable(cache, json, path))
                    .orElseGet(() -> CompletableFuture.completedFuture(null)));
        }
        return CompletableFuture.allOf(futures.toArray(CompletableFuture[]::new));
    }

    @Override
    public @NotNull String getName() {
        return "Champions Tiers";
    }

    // ── Utility ───────────────────────────────────────────────────────────────

    /** Pack ARGB components into an int. Alpha 255 = fully opaque. */
    public static int argb(int a, int r, int g, int b) {
        return (a << 24) | (r << 16) | (g << 8) | b;
    }
}
